name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_HEq4X1EvIXgIqE6tJMizAGn4
          VERCEL_PROJECT_ID: prj_6gKmirbUFOA1NbJSV1DVlnO6hUaw
